### ISSUE TITLE
Bazarr service not starting up - conflicting timezone

### ISSUE THREAD

**Issue by Maximus-CZ** [pijarr/pijarr#24]
After installing bazarr I noticed I cannot connect to its webgui. 
It was not even listed in running service.

I tried running 
` /opt/Bazarr/venv/bin/python /opt/Bazarr/bazarr.py`
manually to see whats up. Here is the outcome:

```console
root@torrentrr:/home/torrentrr# /opt/Bazarr/venv/bin/python /opt/Bazarr/bazarr.py
Bazarr starting...
2024-04-24 12:47:55,696 - root                             (7f3f40e2b040) :  ERROR (scheduler:62) - BAZARR cannot use specified timezone: 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Europe/Prague\nFix the configuration, or set the time zone in a TZ environment variable.\n'
Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/main.py", line 40, in <module>
    from app.signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/app/signalr_client.py", line 25, in <module>
    from .scheduler import scheduler
  File "/opt/Bazarr/bazarr/app/scheduler.py", line 333, in <module>
    scheduler = Scheduler()
                ^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/app/scheduler.py", line 82, in __init__
    self.__cache_cleanup_task()
  File "/opt/Bazarr/bazarr/app/scheduler.py", line 206, in __cache_cleanup_task
    self.aps_scheduler.add_job(cache_maintenance, IntervalTrigger(hours=24), max_instances=1, coalesce=True,
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/../libs/apscheduler/triggers/interval.py", line 46, in __init__
    self.timezone = get_localzone()
                    ^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/../libs/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
                ^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/../libs/tzlocal/unix.py", line 165, in _get_localzone
    tzname = _get_localzone_name(_root)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/../libs/tzlocal/unix.py", line 144, in _get_localzone_name
    raise utils.ZoneInfoNotFoundError(message)
tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Europe/Prague\nFix the configuration, or set the time zone in a TZ environment variable.\n'
Bazarr exited.
root@torrentrr:/home/torrentrr#

```

**Comment by pijarr** [comment]
Have not been able to replicate issue - tested with v1.5.3. No errors.
